version: "3.8"
services:
  web:
    build: .
    ports:
      - "${WEB_PORT:-8080}:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_DATABASE=${DB_DATABASE:-fretecalc_db}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT:-3306}
      - APP_ENV=${APP_ENV:-development}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_SECRET=${APP_SECRET}
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE:-fretecalc_db}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT:-8000}:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST:-db}
      - PMA_USER=${DB_USERNAME:-root}
      - PMA_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
