version: "3.8"
services:
  web:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=fretecalc_db
      - DB_USER=root
      - DB_PASS=G1x45"S;lu0U
      - DB_PORT=3306
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: G1x45"S;lu0U
      MYSQL_DATABASE: fretecalc_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=G1x45"S;lu0U
    depends_on:
      - db

volumes:
  db_data:
